version = 0.1
[default.deploy.parameters]
stack_name = "sam-app-resizer"
resolve_s3 = true
s3_prefix = "sam-app-resizer"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
